---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          # FIXME:<your-org/repo:tag>
          image: bretfisher/wordsmith-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: api
